### ISSUE TITLE
More crypto currencies

### ISSUE THREAD

**Issue by Harish-2003** [OpenTekHub/blockchain#10] opened 2024-09-26 18:24 UTC
For every crypto currencies level1 is assigned 
For 2 level2 is assigned 
For 3 or more level3 will be assigned

**Comment by IshuSinghSE** [comment] 2024-09-29 09:33
Hello! Can I be assigned to this?, How many crypto currencies do I have to add?

**Comment by Harish-2003** [comment] 2024-09-29 09:41
> Hello! Can I be assigned to this?, How many crypto currencies do I have to add?
> 

As many as you want 
Based upon the number of additions the level will be added

**Comment by IshuSinghSE** [comment] 2024-09-29 11:22
Pls assign it to me, I'll be happy to contribute.

**Comment by IshuSinghSE** [comment] 2024-09-29 18:03
please could you add a milestone to my PR, because its not showing in issues as other PR

**Comment by IshuSinghSE** [comment] 2024-10-03 16:53
please close this issue, As the PR for the issue is already merged.

**Closed** 2024-10-03 16:57 UTC
Labels: enhancement, good first issue, help wanted, wob24, level1, level2, level3
